
version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30-node  # Use the appropriate Docker image for your project
    working_directory: ~/project
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError'"
      JDK_VERSION: openjdk11

jobs:
  fastlane-deploy:
    executor: android-executor
    steps:
      - checkout  # Check out the code from your repository
      - run:
          name: Run Fastlane
          command: bundle exec fastlane beta_android # Replace <lane_name> with your lane

workflows:
  version: 2
  deploy:
    jobs:
      - fastlane-deploy


